- hosts: webservers
  vars:
   - project_name: "dev-creatorsbyheart"
   - source_code_dir: "/root/Desktop/playbook_dir/mywebsite/"
   - port_number: 8082
  tasks:
  - name: "create yum repository for docker"
    yum_repository:
      name: docker-repo
      description: "repo for docker"
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      enabled: yes
      gpgcheck: no
    when: ansible_facts['os_family'] == 'RedHat'

  - name: "Install docker"
    package:
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present

  - name: "starting docker service"
    service:
      name: "docker"
      state: started

  - name: "Install pip"
    package:
      name: "python3-pip"
      state: present
      update_cache: true

  - name: "Install docker sdk"
    pip:
     name: "docker"

  - name: "create directory to copy source code"
    file:
      path: "{{ansible_facts['user_dir']}}/{{ project_name }}"
