---
---
- name: copy compose file
  copy:
    src: files/load-balancing
    dest: ~/load-balancing

- name: deploy Docker Compose stack
  command: docker-compose -f ~/load-balancing/docker-compose.yml up -d 
